proyectos/urls.py
from django.conf.urls import url
from django.urls import re_path,include
from proyectos import views
from proyectos.views import CambiarFase, horasTrabajadas, GeneratePDFhorasTrabajadas, GeneratePDFDesempenho
from proyectos.views import HistorialProyecto

app_name = "proyectos"


urlpatterns= [
    # /proyectos/123456.../
    re_path(r"^(?P<pk>\d+)/$", views.detalle, name="detalle"),
    # /proyectos/registrar/
    re_path(r"^registrar/$", views.adicion, name="registrar"),
    # /proyectos/123456.../editar/
    re_path(r"^(?P<pk>\d+)/editar/$", views.modificacion, name="editar"),
    # /proyectos/
    re_path(r"^(?P<pk>\d+)/eliminar/$", views.baja, name="eliminar"),

    url(r'^(?P<pk>\d+)/estado$', views.cambiar_estado, name='estado'),
    re_path(r"^(?P<pk>\d+)/tablero/$", views.ver_tablero, name="ver_tablero"),

    re_path(r"^(?P<pk>\d+)/tablero/cambiar_fase/(?P<uid>\d+)$", CambiarFase.as_view(), name="cambiar_fase"),
    re_path(r"^(?P<pk>\d+)/tablero/agregar_comentario/(?P<uid>\d+)$", views.agregar_comentario, name="agregar_comentario"),
    re_path(r"^(?P<pk>\d+)/tablero/horas/(?P<uid>\d+)$", horasTrabajadas.as_view(), name="horas"),

    url(r'^(?P<pk>\d+)/team/', include("team.urls", namespace="team")),
    url(r'^(?P<pk>\d+)/userstory/', include("userstory.urls", namespace="userstory")),
     url(r'^(?P<pk>\d+)/tipous/', include("tipous.urls", namespace="tipous")),
    # Acceso al Sprint
    url(r'^(?P<pk>\d+)/sprint/', include("sprint.urls", namespace="sprint")),

    url(r'^(?P<pk>\d+)/reporte', GeneratePDFhorasTrabajadas.as_view(),name='reporte'),
    url(r'^(?P<pk>\d+)/desempenho', GeneratePDFDesempenho.as_view(),name='reporte_desempenho'),
    url(r'^(?P<pk>\d+)/historial/', HistorialProyecto.as_view(), name='historial'),
]

sgp/urls.py
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.urls import path
from django.conf.urls import url, include
from .views import PaginaPrincipalView, conectar, desconectar, Historial

app_name = 'sgp'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^principal$',PaginaPrincipalView.as_view(), name='principal'),
    url(r'^historial$',Historial.as_view(), name='historialSistema'),
    url(r'^login', conectar, name='login'),
    url(r'^logout', desconectar, name='logout'),
    url(r'^roles/', include(('roles.urls','roles'), namespace='roles')),
    url(r'^proyecto/', include(('proyectos.urls'), namespace='proyectos')),
    url(r'^usuarios/', include("usuarios.urls", namespace='usuarios')),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proyectos/models.py
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Proyecto(models.Model):
    class Meta:
        """
            Meta-clase de Proyecto:
        Aquí se situan los parámetros de orden del modelo de proyecto y permisos de
        todos las clases que componen un proyecto.
        """
        permissions = (
            ('view_proyecto', 'Ver detalles de un proyecto'),
            ('ver_tablero', 'Ver tablero del proyecto'),
            ('view_historial', 'Ver historial de un proyecto'),
            ('add_Integrante', 'Agregar un integrante al Team'),
            ('edit_Integrante', 'Editar datos de integrante'),
            ('delete_Integrante', 'Eliminar un integrante'),
            ('add_Tus', 'Registrar un tipo de user story'),
            ('edit_Tus', 'Editar datos de un tipo de userstory'),
            ('delete_Tus', 'Eliminar un tipo de user story'),
            ('fases_Tus', 'Manipulacion de las fases del tipo de user story'),
            ('view_Sprint', 'Ver Sprints'),
            ('ver_control','Ver control de calidad en un sprint'),
            ('add_Sprint', 'Crear un Sprint'),
            ('delete_Sprint', 'Descartar un Sprint'),
            ('edit_Sprint', 'Editar Sprint y administrar registro de Reuniones'),
            ('ver_UserStory', 'Ver detalles de un user story'),
            ('ver_ProductBacklog', 'Ver product backlog'),
            ('ver_USfinalizados', 'Ver user stories finalizados'),
            ('crear_UserStory', 'Crear user story'),
            ('modificar_UserStory', 'Modificar user story'),
            ('eliminar_UserStory', 'Eliminar user story'),
        )

        ordering = ["estado","id"]

    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(max_length=1000)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_inicio = models.DateTimeField(null="0000-00-00")
    fecha_fin = models.DateTimeField(null="0000-00-00")
    ultima_modificacion = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=20, default="En espera de inicio")
    logo = models.FileField(default=None, blank=True)

    def __str__(self):
        return "Nombre: " + self.nombre + "\t\tInicio: " + str(self.fecha_inicio) + "\t\tFin: " + str(
            self.fecha_fin) + "\t\tEstado: " + str(self.estado) + "\n"

    def get_absolute_url(self):
        return reverse("proyectos:detalle", kwargs={"pk": self.pk})



class Auditoria(LogEntry):
    proyecto = models.ForeignKey(Proyecto, on_delete=models.SET_NULL,null=True)

team/models.py
from django.contrib.auth.models import User,Group,Permission
from django.db import models
from guardian.shortcuts import assign_perm, remove_perm, get_perms

from proyectos.models import Proyecto

# === Modelos para team ===
class team_member(models.Model):
    """
        Clase team_member:
    Asocia a cada usuario con los proyectos en los cuales participa, y
    con el rol que desempeña dentro de esos proyectos. Además, registra
    las horas diarias disponibles del usuario para dicho proyecto.
    """
    class Meta:
        """
        **Meta-Clase**:
        Define la unicidad de la relacion Usuario-Proyecto, y establece los
        parametros de ordenamiento de los objetos de la clase.
        """
        unique_together = (('usuario', 'proyecto'),)
        ordering = ["rol","proyecto","usuario"]
    usuario = models.ForeignKey(User,on_delete=models.CASCADE)
    proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
    rol = models.ForeignKey(Group,on_delete=models.SET_NULL,null=True)
    horas_trabajo= models.IntegerField(default=4)
    horas_trabajadas=models.IntegerField(default=0)
    def __str__ (self):
        """
        `Override:` personaliza la representación en formato "cadena" del objeto.
        """
        try:
            usuario=self.usuario.username
        except:
            usuario=""
        try:
            rol_asignado=self.rol.name
        except :
            rol_asignado="?"
        try:
            proyecto=self.proyecto.nombre
        except :
            proyecto_in=""

        return  "%s" %(usuario)

    def save(self, force_insert=False, force_update=False, using=None,update_fields=None):
        """
        `Override:` dada la alta o modificación de un team member, otorga los permisos
        correspondientes al rol asignado al usuario integrante; y  quita los permisos
        que poseía anteriormente sobre dicho objeto.
        """
        old = team_member.objects.filter(id=self.id)
        if old.count()> 0 :
            for x in get_perms(self.usuario,self.proyecto):
                print("Remover " + x + " a " + self.usuario.username + " en " + self.proyecto.nombre)
                remove_perm(x,self.usuario,self.proyecto)
        super().save(force_insert=force_insert,
                     force_update=force_update,
                     using=using,
                     update_fields=update_fields)
        rol=self.rol
        if rol == None:
            x=Permission.objects.get(codename="view_proyecto")
            print("Conceder " + x.codename + " a " + self.usuario.username + " en " + self.proyecto.nombre)
            assign_perm(x.codename, self.usuario, self.proyecto)
        else:
            for x in rol.permissions.all():
                if x.content_type.name == 'proyecto':
                    print("Conceder " + x.codename + " a "+self.usuario.username+" en "+self.proyecto.nombre)
                    assign_perm(x.codename,self.usuario,self.proyecto)


    def delete(self, *args, **kwargs):
        """
        `Override:` quita los permisos del usuario sobre el proyecto del cual
        ha sido expulsado.
        """
        old = team_member.objects.filter(id=self.id)
        if old.count() > 0:
            for x in get_perms(self.usuario, self.proyecto):
                print("Remover " + x + " a " + self.usuario.username + " en " + self.proyecto.nombre)
                remove_perm(x, self.usuario, self.proyecto)
        super().delete(*args, **kwargs)

templates/proyectos/actualizar_horas.html
<div class="modal fade" id="horasTrabajadas_{{ us.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<form method="post" action="{% url "proyectos:horas" proyecto.id us.id %}">
  {% csrf_token %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div>
            <h3 class="modal-title" id="exampleModalLabel"><strong>Cargar horas trabajadas a {{ us.nombre }}</strong></h3>
        </div>
      </div>
      <div class="modal-body">
        <div>
          <tr>
            <th><label>Tiempo estimado del US: </label> {{ us.tiempo_estimado }} horas</th><br>
            <th><label>Tiempo dedicado actualmente: </label> {{ us.tiempo_dedicado }} horas</th><br>
            <th><label for="id_tiempo_dedicado">Horas:</label></th>
            <td><input type="number" name="tiempo_dedicado" id="id_tiempo_dedicado" min="0" required /></td>
          </tr>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <input class="btn btn-primary" type="submit" value="Guardar Cambios" />
      </div>
    </div>
  </div>
</form>
</div>

templates/proyectos/cambioestado.html
<div class="modal fade" id="cambio_estado" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<form method="post" action="{% url "proyectos:estado" proyecto.id%}">
  {% csrf_token %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div>
           <h3 class="modal-title" id="exampleModalLabel">
              <strong>
                {% if to == "Activo" %}Iniciar Proyecto
                {% elif to == "Finalizado" %}Finalizar Proyecto{% endif %}
              </strong>
           </h3>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ¿Desea modificar el estado a "{{ to }}"?
      </div>
      <input name="estado" value="{{ to }}" hidden />
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <input class="btn btn-primary" type="submit" value="Aceptar" />
      </div>
    </div>
  </div>
</form>
</div>
<div class="modal fade" id="cancelar_proyecto" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<form method="post" action="{% url "proyectos:estado" proyecto.id%}">
  {% csrf_token %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div>
           <h3 class="modal-title" id="exampleModalLabel">
              <strong>
                  Cancelar Proyecto
              </strong>
           </h3>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ¿Desea modificar el estado a "Proyecto Cancelado"?
      </div>
      <input name="estado" value="Proyecto Cancelado" hidden />
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <input class="btn btn-primary" type="submit" value="Aceptar" />
      </div>
    </div>
  </div>
</form>
</div>

templates/proyectos/detalle.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_proyectos.html" with proyecto=proyecto proyecto_active=True %}
{% endblock %}

{% block title %}
    Proyectos | Detalles: {{ proyecto.nombre }}
{% endblock %}


{% block content %}
    {% load guardian_tags %}
    {% if proyecto %}
        {% get_obj_perms request.user for proyecto as "US_perms" %}
        <div class="container">
        <div class="row">
        <div class="col-sm-5 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url "proyectos:detalle" proyecto.id %}">
                        {% if proyecto.logo %}
                            <img src="{{ proyecto.logo.url }}" class="img-responsive" alt="Logo">
                        {% else %}
                            <h5>No hay imagen para mostrar</h5>
                        {% endif %}
                    </a>
                    <h1>{{ proyecto.nombre }} <br><small>{{ proyecto.estado }}</small></h1>
                    <h2>Creado el {{ proyecto.fecha_creacion.date |date:"d/m/Y" }}</h2>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-6">
            <meta charset="UTF-8">
            <title>{{ proyecto.nombre }}</title>
            <h1>
                <strong>Detalles de {{ proyecto.nombre }}</strong>&nbsp;
                {% csrf_token %}
                {% get_obj_perms request.user for proyecto as "Tipous_perms" %}
                {% if "view_historial" in Tipous_perms %}
                     {% if proyecto.estado != "Proyecto Cancelado" and proyecto.estado != "Finalizado" %}
                     <a href="historial/" style="display: inline">
                        <button type="submit" class="btn btn-primary" data-toggle="tooltip" title="Historial del Proyecto">
                            <span class="glyphicon glyphicon-time"/>
                        </button>
                    </a>
                         {% endif %}
                {% endif %}
                <a href="{% url "proyectos:editar" proyecto.id %}" style="display: inline" >
                <button type="submit" class="btn btn-primary" data-toggle="tooltip" title="Editar Proyecto">
                    <span class="glyphicon glyphicon-edit"></span>
                </button>
                </a>
                <a href="{% url "proyectos:eliminar" proyecto.id %}" style="display: inline">
                    <button type="submit" class="btn btn-danger" data-toggle="tooltip" title="Borrar Proyecto">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </a>
                <p>


                {% if "add_Tus" in Tipous_perms %}
                     {% if proyecto.estado != "Proyecto Cancelado" and proyecto.estado != "Finalizado" %}
                    <a href="tipous/" style="display: inline">
                        <button type="submit" class="btn btn-primary">
                            Tipos de User Story
                        </button>
                    </a>
                         {% endif %}
                {% endif %}
                {% get_obj_perms request.user for proyecto as "backlog_perms" %}
                {% if "ver_tablero" in backlog_perms %}
                     {% if proyecto.estado != "Proyecto Cancelado" and proyecto.estado != "Finalizado" %}
                    <a href="tablero/" style="...">
                        <button type="submit" class="btn btn-primary">
                            Ver tablero
                        </button>
                    </a>
                         {% endif %}
                {% endif %}
                </p>
            </h1><br>

            <strong>Nombre:</strong> {{ proyecto.nombre }}<br>
            <strong>Descripción:</strong> {{ proyecto.descripcion }}<br>
            <strong>Fecha de creación:</strong> {{ proyecto.fecha_creacion |date:"d/m/Y" }}<br>
            <strong>Fecha de inicio del proyecto:</strong> {{ proyecto.fecha_inicio.date | date:"d/m/Y" }}<br>
            <strong>Fecha de finalización del proyecto:</strong> {{ proyecto.fecha_fin.date |date:"d/m/Y" }}<br>
            <strong>Última modificación:</strong> {{ proyecto.ultima_modificacion | date:"d/m/Y H:i" }}<br>
            <strong>Estado del proyecto:</strong> {{ proyecto.estado }}<br>
            {% if proyecto.estado == "En espera de inicio" %}
            <a data-toggle="modal" href="#cambio_estado">
                <button class="btn btn-success">
                    <span class="glyphicon glyphicon-play"></span>
                    Empezar Proyecto
                </button>
            </a>
            {% include "proyectos/cambioestado.html" with proyecto=object to="Activo"%}
            {% endif %}
            {% if proyecto.estado == "Activo" %}
                <a data-toggle="modal" href="#cambio_estado">
                <button class="btn btn-success">
                    <span class="glyphicon glyphicon-stop"></span>
                    Finalizar Proyecto
                </button>
                </a>
                {% include "proyectos/cambioestado.html" with to="Finalizado"%}
            {% endif %}
            {% if proyecto.estado == "En espera de inicio" or  proyecto.estado == "Activo" %}
                <a data-toggle="modal" href="#cancelar_proyecto">
                <button class="btn btn-success">
                    <span class="glyphicon glyphicon-eject"></span>
                    Cancelar Proyecto
                </button>
                </a>
            {% endif %}
            <p></p><br>

        </div>
        </div>
        <div class="row">
            {% if "ver_ProductBacklog" in backlog_perms %}
            <div class="col-sm-4 col-md-4">
                <h2>User Stories
                    <a href="userstory/product_backlog/" style="...">
                        <button class="btn btn-primary">Product Backlog</button>
                    </a>
                </h2>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <td><strong>Nombre</strong></td>
                        <td><strong>Estado</strong></td>
                        <td><strong>Prioridad</strong></td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for us in proyecto.userstory_set.all %}
                        <tr>
                            <td>{{ us.nombre }}</td>
                            <td>{{ us.get_estado_display }}</td>
                            <td>{{ us.prioridad_final }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
            <div class="col-sm-4 col-md-4">
                <h2>Team  {% if proyecto.estado != "Proyecto Cancelado" and proyecto.estado != "Finalizado" %}<a class="btn btn-primary" href="team/">Ver</a>
                {% endif %}
                    <a class="btn btn-primary" href="reporteHorasTrabajadas/">Ver Reporte</a><br></h2>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <td><strong>Nombre</strong></td>
                        <td><strong>Usuario</strong></td>
                        <td><strong>Rol</strong></td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for team_member in proyecto.team_member_set.all %}
                        <tr>
                            <td>{{ team_member.usuario.first_name }}</td>
                            <td>{{ team_member.usuario.get_username }}</td>
                            {% if team_member.rol.name == None %}
                                <td><u><i>Sin Rol</i></u></td>
                            {% else %}
                                <td>{{ team_member.rol.name}}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-sm-4 col-md-4">

                {% if permiso_view_sprint %}
                    <h2>Sprints {% if proyecto.estado != "Proyecto Cancelado" and proyecto.estado != "Finalizado" %}
                        <a class="btn btn-primary" href="sprint/">Ver</a>
                        <a class="btn btn-primary" href="desempenho/">Trabajo Realizado</a>{% endif %}
                    </h2>

                <br>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <td><strong>Fecha de Inicio</strong></td>
                        <td><strong>Fecha de Fin</strong></td>
                        <td><strong>Estado</strong></td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for sprint in proyecto.sprint_set.all %}
                        <tr>
                            {% if sprint.fechaInicio == None %}
                                <td><u><i>No definida</i></u></td>
                            {% else %}
                                <td>{{sprint.fechaInicio | date:"d/m/Y"}}</td>
                            {% endif %}
                            {% if sprint.fechaFinalizacion == None %}
                                <td><u><i>No definida</i></u></td>
                            {% else %}
                                <td>{{sprint.fechaFinalizacion | date:"d/m/Y"}}</td>
                            {% endif %}
                            <td> {{ sprint.estado }} </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% endif %}

            </div>

            </div>
        </div>
        {% else %}
            <h1>No existe el proyecto especificado</h1>
        {% endif %}
</div>

{% endblock %}

templates/proyectos/historial.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_proyectos.html"  %}
{% endblock %}

{% block title %}
    Logs del Proyecto
{% endblock %}

{% block content %}

    <div class="container center-block">
        <div class="container-fluid">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h1>
                    <p class="text-center">Proyecto {{ proyecto.nombre }}: Historial</p>
                </h1>
            </div>
            <div class="panel-body">
                <p></p>
                <a class= "btn btn-default" href="/proyecto/{{ proyecto.id }}">Volver al proyecto</a>

                <table class="table table-bordered">
                    <div><p> </p></div>
                    <thead>
                        <tr>
                            <td><b><center>Hora</center></b></td>
                            <td><b><center>Clase</center></b></td>
                            <td><b><center>Nombre</center></b></td>
                            <td><b><center>Mensaje</center></b></td>
                            <td><b><center>Nombre del miembro</center></b></td>
                            <td><b><center>Rol</center></b></td>

                        </tr>
                    </thead>
                    <tbody>
                        <div></div>
                        {% if object_list %}
                            {% for auditoria in object_list %}
                                <tr>
                                    <td>{{ auditoria.action_time | date:"d/m/Y H:i" }}</td>
                                    <td>{{ auditoria.content_type }}</td>
                                    <td>{{ auditoria.object_repr }}</td>
                                    <td>{{ auditoria.change_message }}</td>
                                    {% for team_member in auditoria.proyecto.team_member_set.all %}
                                        {% if team_member.usuario.id == auditoria.user_id %}

                                            <td>{{ team_member.usuario.get_username }}</td>
                                            {% if team_member.rol.name == None %}
                                                <td><u><i>Sin Rol</i></u></td>
                                            {% else %}
                                                <td>{{ team_member.rol.name}}</td>
                                            {% endif %}
                                         {% endif %}
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        {% else %}
                            <h2>No hay registros de historial</h2>
                            <div><p> </p></div>
                        {% endif %}
                    </tbody>
                </table>
                <ul class="pagination">
                    <li class="page-item">
                        {% if page_obj.has_previous %}
                         <a class="page-link" aria-label="Anterior" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                        {% endif %}
                    </li>
                    <li>
                        {% if page_obj.has_next %}
                         <a class="page-link" aria-label="Siguiente" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

templates/proyectos/proyecto_confirm_delete.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_proyectos.html" with proyecto=proyecto %}
{% endblock %}

{% block proyectos_active %}
    active
{% endblock %}

{% block title %}
    Proyectos | Eliminar: {{ proyecto.nombre }}
{% endblock %}

{% block content %}
    <form action="" method="post">
        <div class="container">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h1>
                        <p class="text-center">¿Está seguro que desea eliminar el proyecto {{ proyecto.nombre }}?</p>
                    </h1>
                </div>
                <div class="panel-body">
                    <p class="text-center">
                        <input class="boton_eliminar" type="submit" value="Eliminar" style='width:125px; height:50px'/>&nbsp;
                        {% csrf_token %}
                        <button onclick="window.history.back();" class="boton_cancelar" type="button" style='width:125px; height:50px'>
                            Cancelar
                        </button>
                    </p>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/proyectos/proyecto_form.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_sistema.html" with proyectos_active=True %}
{% endblock %}

<!-- BOTÓN ACTIVO -->
{% block proyectos_active %}
    active
{% endblock %}

{% block title %}
    Proyectos | Nuevo Proyecto
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h1>
                    <p class="text-center">Nuevo proyecto</p>
                </h1>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include "field_form.html" %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <p class="text-center">
                                <button type="submit" class="boton_alta">
                                    Crear proyecto
                                </button>&nbsp;
                                <button onclick="window.history.back();" class="boton_cancelar">
                                    Cancelar
                                </button>
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/proyectos/proyecto_update_form.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_proyectos.html" with proyecto=proyecto %}
{% endblock %}

{% block proyectos_active %}
    active
{% endblock %}

{% block title %}
    Proyectos | Editar: {{ proyecto.nombre }}
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1>
                    <p class="text-center">Editar proyecto: {{ proyecto.nombre }}</p>
                </h1>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include "field_form.html" %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <p class="text-center">
                                <input class="boton_editar" type="submit" value="Guardar" style='width:125px; height:50px'/>&nbsp;
                                <button onclick="window.history.back();" class="boton_cancelar" type="button" style='width:125px; height:50px'>
                                    Cancelar
                                </button>
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}