roles/urls.py
from django.conf.urls import url
from django.contrib.auth.models import Group

from roles.views import listar_rol, crear_rol_view, modificar_rol, eliminar_rol, detalle_rol

urlpatterns = [
    url(r'^listar_rol$', listar_rol.as_view(model=Group,), name='listar'),
    url(r'^crear_rol$', crear_rol_view, name='crear'),
    url(r'^modif_rol/(?P<pk>\d+)/$', modificar_rol.as_view(model=Group,), name='modificar'),
    url(r'^eliminar_rol/(?P<pk>\d+)/$', eliminar_rol.as_view(model=Group,), name='eliminar'),
    url(r'^detalle_rol/(?P<pk>\d+)/$', detalle_rol.as_view(model=Group,), name='ver'),
]

sgp/urls.py
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.urls import path
from django.conf.urls import url, include
from .views import PaginaPrincipalView, conectar, desconectar, Historial

app_name = 'sgp'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^principal$',PaginaPrincipalView.as_view(), name='principal'),
    url(r'^historial$',Historial.as_view(), name='historialSistema'),
    url(r'^login', conectar, name='login'),
    url(r'^logout', desconectar, name='logout'),
    url(r'^roles/', include(('roles.urls','roles'), namespace='roles')),
    url(r'^proyecto/', include(('proyectos.urls'), namespace='proyectos')),
    url(r'^usuarios/', include("usuarios.urls", namespace='usuarios')),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

roles/models.py
from django.contrib.auth.models import Group
from django.db import models

roles/forms.py
from django import forms
from django.contrib.auth.models import Group

"""
Form de la aplicación roles:

1. **GroupForm** - usado para la edicion y creación de roles


"""


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            'name',
            'permissions',
        ]
        labels = {
            'name':'Nombre del rol',
            'permissions':'Permisos',
        }
        widgets = {
            'permissions': forms.SelectMultiple(attrs={'style': 'width: 450px; height: 350px;'})
        }

roles/views.py
from django.contrib.admin.models import ADDITION, CHANGE, DELETION
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Group,Permission
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, DetailView

from proyectos.models import Proyecto
from roles.forms import GroupForm
from sgp.views import historial2, historial
from team.models import team_member

"""
La aplicacion roles actualmente 
soporta las siguientes 5 vistas:


1. **listar_rol** - Vista para la lista de roles
2. **crear_rol_view** - Vista para la creación de un rol
3. **modificar_rol** - Vista para la modificación de un rol
4. **eliminar_rol** - Vista para la eliminación de un rol
5. **detalle_rol** - Vista para visualizar detalles de un rol

"""
# Las pruebas unitarias de las vistas se encuentran en [[tests.py]]

# === crear_rol ===
@login_required
@permission_required('auth.add_group')
def crear_rol_view(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            historial2(request,form,ADDITION,'Nuevo Rol')
            return redirect('roles:listar')
        else:
            return redirect(reverse_lazy('roles:listar') + "?err_name=True")
    else:
        form = GroupForm()
        tipo_proyecto = ContentType.objects.get_for_model(Proyecto)
        lista = Permission.objects.filter(content_type=tipo_proyecto).exclude(codename="add_proyecto")

    return render(request,'roles/roles_form.html', {'form': form,
                                                    'lista_permisos': lista})


# === listar_roles ===
class listar_rol(PermissionRequiredMixin,ListView):
    """
    **Ancestros**

    1. PermissionRequiredMixin: CBV mixin que verifica que el usuario actual tiene todos los permisos especificados

    2. ListView: Renderiza alguna lista de objetos.

    **Retorna:** url a listar_rol
    """
    model = Group
    template_name = "roles/rol_listar.html"
    paginate_by = 8
    permission_required = 'auth.change_group'

    def get_context_data(self, *, object_list=None, **kwargs):
        contexto = super().get_context_data()
        if "err_name" in self.request.GET:
            contexto["nombre_no_disponible"]= self.request.GET["err_name"] == "True"
        return contexto



# === modificar_rol ===
class modificar_rol(PermissionRequiredMixin,UpdateView):
    """

    **Ancestros:**

    1. PermissionRequiredMixin: CBV mixin que verifica que el usuario actual tiene todos los permisos especificados

    2. UpdateView: Vista para modificar un objeto,con una respuesta renderizada por un template

    **Retorna**: url a listar_rol
    """

    model = Group
    form_class = GroupForm
    permission_required = 'auth.change_group'
    template_name = 'roles/roles_form.html'

    def get_success_url(self):
        # `Override:` Dado un exito en la operación, actualiza los permisos de los integrantes (en sus
        # equipos) que poseen el rol modificado.
        for integrante in team_member.objects.filter(rol=self.object):
            integrante.save()
        historial(self,CHANGE,'Modificacion de Rol')
        return reverse_lazy('roles:listar')

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        tipo_proyecto=ContentType.objects.get_for_model(Proyecto)
        if self.object.name == "Administrador" or self.object.name == "Usuario Normal":
            add_proy = Permission.objects.filter(codename="add_proyecto")
            contexto["lista_permisos"] = Permission.objects.exclude(content_type=tipo_proyecto)
            contexto["lista_permisos"] = contexto["lista_permisos"].union(add_proy)
        else:
            contexto["lista_permisos"] = Permission.objects.filter(content_type=tipo_proyecto)
            contexto["lista_permisos"] = contexto["lista_permisos"].exclude(codename="add_proyecto")

        return contexto

    def form_invalid(self, form):
        return redirect(reverse_lazy('roles:listar') + "?err_name=True")

# === eliminar_rol ===
class eliminar_rol(PermissionRequiredMixin,DeleteView):
    """

    **Ancestros:**

    1. PermissionRequiredMixin: CBV mixin que verifica que el usuario actual tiene todos los permisos especificados

    2. DeleteView: Vista para borrar un objeto recolectado con  `self.get_object()`, con una respuesta renderizada con una template

    **Retorna:** url a listar_rol
    """

    model = Group
    permission_required = 'auth.delete_group'
    template_name = 'roles/rol_eliminar.html'
    def get_success_url(self):
        # `Override:` Dado un exito en la operación, desacredita los permisos al los integrantes afectados
        for integrante in team_member.objects.filter(rol=self.object):
            integrante.save()
        historial(self,DELETION,'Borrado de Rol')
        return reverse_lazy('roles:listar')


# === detallo_rol ===
class detalle_rol(DetailView):
    """
    **Ancestros:**

    1.DetailView: por defecto esta es una instancia
        de modelo para `self.queryset` pero
        la vista soporta mostrar cualquier
        objeto si se sobreescribe `self.get_object()

    **Retorna:** Renderiza la vista detalle del objeto
    """

    template_name = "roles/rol_detalle.html"

templates/roles/rol_detalle.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_sistema.html" with rol_active=True%}
{% endblock %}

{% block title %}
    Roles | Detalles: {{ object.name }}
{% endblock %}

{% block content %}
    <div class="container pt-5 ">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label><b>Nombre del rol: </b>{{ object.name }}</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label ><b>Permisos: </b>
                        <div class="pre-scrollable">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <td><center>Id</center></td>
                                    <td><center>Permiso</center></td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for x in object.permissions.all %}
                                    <tr>
                                        <td>{{ x.id }}</td>
                                        <td>{{ x.name }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        </div>
                        <!--<p>{{ object.permissions.all }}</p>-->
                    </label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <a class= "btn btn-default" href="{% url 'roles:listar' %}">Atrás</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/roles/rol_eliminar.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_sistema.html" with rol_active=True%}
{% endblock %}

{% block title %}
    Roles | Eliminar: {{ object.name }}
{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
    <div class="container center-block">
	    <h5>¿Desea eliminar el rol {{ object.name }}?</h5>
	    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
	    <a class= "btn btn-default" href="{% url 'roles:listar' %}">Cancelar</a>
    </div>
</form>
{% endblock %}

templates/roles/rol_listar.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_sistema.html" with rol_active=True%}
{% endblock %}

<!-- BOTÓN ACTIVO -->
{% block roles_active %}
    active
{% endblock %}

{% block title %}
    Roles | Lista de Roles
{% endblock %}

{% block content %}
    {% if nombre_no_disponible%}
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-alert"> </span>
                    El nombre de Rol no está disponible
                </div>
            </div>
        </div>
    {% endif %}
    <h3><center> Lista de Roles </center></h3>
    <div class="container pt-3 ">
        <table class="table table-bordered">
            <p align="right"><a class="btn btn-primary" href="{% url 'roles:crear' %}">Añadir rol</a></p>
        <thead>
            <tr>
                <td><center><b>Nro</b></center></td>
                <td><center><b>Nombre del Rol</b></center></td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
                <h6><b>Roles de Sistema</b></h6>
                {% for group in object_list|dictsort:"id" %}
                    {% if  group.name == "Administrador" or group.name == "Usuario Normal" %}
                        <tr>
                            <td>{{ group.id }}</td>
                            <td>{{ group.name}}</td>
                            <td align="center">
                                {% if perms.auth.change_group %}<a class="btn btn-primary" href="{% url 'roles:modificar' group.id %}" >Editar</a>{% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% else %}
                <h1>No hay registros de roles</h1>
            {% endif %}
        </tbody>
        </table>
        <table class="table table-bordered">
            <thead>
            <tr>
                <td><center><b>Nro</b></center></td>
                <td><center><b>Nombre del Rol</b></center></td>
            </tr>
            </thead>
            <tbody>
            {% if object_list %}
                <h6><b>Roles de Team</b></h6>
                {% for group in object_list|dictsort:"id" %}
                    {% if  group.name != "Administrador" and group.name != "Usuario Normal" %}
                        <tr>
                            <td>{{ group.id }}</td>
                            <td>{{ group.name}}</td>
                            <td align="center">
                                <a class="btn btn-info" href="{% url 'roles:ver' group.id %}">Ver</a>
                                {% if perms.auth.change_group %}<a class="btn btn-primary" href="{% url 'roles:modificar' group.id %}">Editar</a>{% endif %}
                                {% if perms.auth.delete_group %}<a class="btn btn-danger" href="{% url 'roles:eliminar' group.id %}">Eliminar</a>{% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% else %}
                <h1>No hay registros de roles</h1>
            {% endif %}
            </tbody>
        </table>
        <ul class="pagination">
            <li class="page-item">
                {% if page_obj.has_previous %}
                    <a class="page-link" aria-label="Anterior" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}
            </li>
            <li>
                {% if page_obj.has_next %}
                    <a class="page-link" aria-label="Siguiente" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                {% endif %}
            </li>
        </ul>

    </div>
{% endblock %}
<a class="btn btn-primary" href="{% url 'roles:ver' group.id %}">Ver</a>

templates/roles/rol_modificar.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_sistema.html" with rol_active=True%}
{% endblock %}

{% block title %}
    Roles | Editar: {{ object.name }}
{% endblock %}

{% block content %}
    <div class="container pt-3 ">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Guardar Cambios</button>
            <a class= "btn btn-default" href="{% url 'roles:listar' %}">Cancelar</a>
        </form>
    </div>

{% endblock %}

templates/roles/roles_form.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_sistema.html" with rol_active=True%}
{% endblock %}

{% block title %}
    Roles | {% if object %}Editar rol{% else %}Nuevo Rol{% endif %}
{% endblock %}

{% block content %}
    <div class="container center-block pt-3">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="form-group">
                        <label>Nombre del Rol:</label>
                        <input class="form-control" type="text" name="name" value="{{ object.name }}" required>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="form-group">
                        <label>Permisos:</label>
                        <div class="pre-scrollable">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <td>#</td>
                                <td>Permiso</td>
                            </thead>
                            <tbody>
                            {% for perm in lista_permisos|dictsort:"id" %}
                                <tr>
                                    <td>
                                        <input type="checkbox" name="permissions" value="{{ perm.id }}"
                                            {% if perm in object.permissions.all %}checked{% endif %} onclick="ver(1)"/>
                                    </td>
                                    <td>
                                        {{ perm.name }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="form-group">
                        <button onclick="ver(0)" class="btn btn-primary" type="submit">Guardar</button>
                        <a class= "btn btn-default" href="{% url 'roles:listar' %}">Cancelar</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <script>
        function ver(cant) {
            var i;
            var mensaje = "";
            var boxes = $("input[name=permissions]:checked");
            var all_boxes = $("input[name=permissions]");
            if (cant == 0){
                mensaje = "Seleccione al menos un Permiso para el Rol"
            }
            console.log(cant)
            if (boxes.length == cant ){
                for (i=0;i<all_boxes.length;i++){
                    all_boxes[i].setCustomValidity(mensaje);
                }
            }
        }
    </script>
{% endblock %}