sgp/urls.py
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.urls import path
from django.conf.urls import url, include
from .views import PaginaPrincipalView, conectar, desconectar, Historial

app_name = 'sgp'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^principal$',PaginaPrincipalView.as_view(), name='principal'),
    url(r'^historial$',Historial.as_view(), name='historialSistema'),
    url(r'^login', conectar, name='login'),
    url(r'^logout', desconectar, name='logout'),
    url(r'^roles/', include(('roles.urls','roles'), namespace='roles')),
    url(r'^proyecto/', include(('proyectos.urls'), namespace='proyectos')),
    url(r'^usuarios/', include("usuarios.urls", namespace='usuarios')),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sprint/urls.py
from django.conf.urls import url




from .views import crear, editar, borrar, listar, importar, ver, crear_resumen, editar_resumen, borrar_resumen, \
    pasar_estado, GeneratePDF, Control, ControlEditar, GeneratePDFSprintBacklog, ControlScrum, BurndownChartDetailView, \
    GeneratePDFusprioridad

app_name = 'sprint'
urlpatterns = [
    url(r'^$', listar, name='list'),
    url(r'^add$', crear, name='agregar'),
    url(r'^importar$',importar , name='importar'),
    url(r'^importar/(?P<s>\d+)$',importar , name='importar_sprint'),
    url(r'^(?P<sp>\d+)$', ver, name='ver'),
    url(r'^(?P<sp>\d+)/controlscrum$', ControlScrum.as_view(), name='controlscrum'),
    url(r'^(?P<sp>\d+)/control$',Control.as_view(), name='control'),
    url(r'^(?P<sp>\d+)/control/(?P<usid>\d+)$', ControlEditar.as_view(), name='control_editar'),
    url(r'^(?P<sp>\d+)/borrar$', borrar, name='borrar'),
    url(r'^(?P<sp>\d+)/editar$', editar, name='editar'),
    url(r'^(?P<sp>\d+)/continuar$', pasar_estado, name='continuar'),
    url(r'^(?P<sp>\d+)/pdf$', GeneratePDFSprintBacklog.as_view(), name='pdf'),
    url(r'^(?P<sp>\d+)/pdfUS$', GeneratePDFusprioridad.as_view(), name='pdfus'),
    url(r'^(?P<sp>\d+)/pdf/(?P<tid>\d+)$', GeneratePDF.as_view(), name='pdf'),
    url(r'^(?P<sp>\d+)/add/$', crear_resumen, name='agregar_resumen'),
    url(r'^(?P<sp>\d+)/(?P<r>\d+)$', ver, name='ver_resumen'),
    url(r'^(?P<sp>\d+)/borrar/(?P<r>\d+)$', borrar_resumen, name='borrar_resumen'),
    url(r'^(?P<sp>\d+)/editar/(?P<r>\d+)$', editar_resumen, name='editar_resumen'),
    url(r'^(?P<sp>\d+)/burndownchart/$', BurndownChartDetailView.as_view(), name='burndown_chart'),
]

sprint/models.py
import datetime

from django.contrib.postgres.fields import ArrayField
from django.db import models


from sgp.settings import MEDIA_ROOT
from team.models import team_member
from userstory.models import UserStory
from proyectos.models import Proyecto

# === Modelos para sprint ===
class Sprint (models.Model):
    """
        Clase Sprint:
    Soporte para la seleccion de labores a cumplir en un determinado tiempo de ejecución.
    Las labores a contemplar serán determinadas en la clase UserStory
    """
    class Meta:
        """
        **Meta-Clase**:
        Establece los parametros de ordenamiento de los objetos de la clase.
        """
        ordering = ["estado","fechaFinalizacion"]
    estado = models.CharField(max_length=18,default="En espera")
    sprintBacklog = models.ManyToManyField(UserStory)
    sprintTeam = models.ManyToManyField(team_member)
    duracion = models.PositiveIntegerField(default=5)
    fechaInicio = models.DateField(null=True)
    fechaFinalizacion = models.DateField(null=True)
    proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
    notificadoFin = models.CharField(max_length=5,default='No')

    def __str__(self):
        return str(self.id)+str(self.proyecto.nombre)

    def save(self, force_insert=False, force_update=False, using=None,update_fields=None):
        if(self.estado!="En espera" and self.estado!="En ejecución" and self.estado!="Finalizado"):
            print("Estado no valido : "+self.estado)
            self.estado="En espera"
        if (self.fechaInicio!=None and self.fechaFinalizacion==None):
            calendario = datetime.timedelta(max(self.duracion-1,0))
            self.fechaFinalizacion = calendario + self.fechaInicio
        super().save(force_insert=force_insert,
                     force_update=force_update,
                     using=using,
                     update_fields=update_fields)

class reuniones (models.Model):
    """
        Clase Reuniones:
    Clase auxiliar que posibilita el registro de pequeñas reuniones retrospectivas dentro del Sprint.
    """
    class Meta:
        """
        **Meta-Clase**:
        Establece los parametros de ordenamiento de los objetos de la clase.
        """
        ordering = ["-fecha"]
    fecha = models.DateField()
    titulo = models.CharField(max_length=55)
    resumen = models.CharField(max_length=280)
    sprint = models.ForeignKey(Sprint,on_delete=models.CASCADE)


class BurndownChart(models.Model):
    sprint = models.ForeignKey(Sprint, on_delete=models.CASCADE)
    horas_restantes = models.IntegerField(default=0)
    contador_dias = models.IntegerField(default=1)
    ultima_fecha = models.DateField(auto_now_add=True)
    abscisas = ArrayField(models.DateField(), blank=True)
    ordenadas = ArrayField(models.IntegerField(blank=True), blank=True)

team/models.py
from django.contrib.auth.models import User,Group,Permission
from django.db import models
from guardian.shortcuts import assign_perm, remove_perm, get_perms

from proyectos.models import Proyecto

# === Modelos para team ===
class team_member(models.Model):
    """
        Clase team_member:
    Asocia a cada usuario con los proyectos en los cuales participa, y
    con el rol que desempeña dentro de esos proyectos. Además, registra
    las horas diarias disponibles del usuario para dicho proyecto.
    """
    class Meta:
        """
        **Meta-Clase**:
        Define la unicidad de la relacion Usuario-Proyecto, y establece los
        parametros de ordenamiento de los objetos de la clase.
        """
        unique_together = (('usuario', 'proyecto'),)
        ordering = ["rol","proyecto","usuario"]
    usuario = models.ForeignKey(User,on_delete=models.CASCADE)
    proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
    rol = models.ForeignKey(Group,on_delete=models.SET_NULL,null=True)
    horas_trabajo= models.IntegerField(default=4)
    horas_trabajadas=models.IntegerField(default=0)
    def __str__ (self):
        """
        `Override:` personaliza la representación en formato "cadena" del objeto.
        """
        try:
            usuario=self.usuario.username
        except:
            usuario=""
        try:
            rol_asignado=self.rol.name
        except :
            rol_asignado="?"
        try:
            proyecto=self.proyecto.nombre
        except :
            proyecto_in=""

        return  "%s" %(usuario)

    def save(self, force_insert=False, force_update=False, using=None,update_fields=None):
        """
        `Override:` dada la alta o modificación de un team member, otorga los permisos
        correspondientes al rol asignado al usuario integrante; y  quita los permisos
        que poseía anteriormente sobre dicho objeto.
        """
        old = team_member.objects.filter(id=self.id)
        if old.count()> 0 :
            for x in get_perms(self.usuario,self.proyecto):
                print("Remover " + x + " a " + self.usuario.username + " en " + self.proyecto.nombre)
                remove_perm(x,self.usuario,self.proyecto)
        super().save(force_insert=force_insert,
                     force_update=force_update,
                     using=using,
                     update_fields=update_fields)
        rol=self.rol
        if rol == None:
            x=Permission.objects.get(codename="view_proyecto")
            print("Conceder " + x.codename + " a " + self.usuario.username + " en " + self.proyecto.nombre)
            assign_perm(x.codename, self.usuario, self.proyecto)
        else:
            for x in rol.permissions.all():
                if x.content_type.name == 'proyecto':
                    print("Conceder " + x.codename + " a "+self.usuario.username+" en "+self.proyecto.nombre)
                    assign_perm(x.codename,self.usuario,self.proyecto)


    def delete(self, *args, **kwargs):
        """
        `Override:` quita los permisos del usuario sobre el proyecto del cual
        ha sido expulsado.
        """
        old = team_member.objects.filter(id=self.id)
        if old.count() > 0:
            for x in get_perms(self.usuario, self.proyecto):
                print("Remover " + x + " a " + self.usuario.username + " en " + self.proyecto.nombre)
                remove_perm(x, self.usuario, self.proyecto)
        super().delete(*args, **kwargs)

templates/sprint/add.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_proyectos.html" with proyecto=proyecto sprint_active=True %}
{% endblock %}

{% block title %}
    Sprints | Nuevo Sprint
{% endblock %}

{% block content %}
<div class="container pt-3 ">
    <form method="post">
        <a class= "btn btn-default" href={% url "proyectos:sprint:list" proyecto.id %}>Volver a la lista de Sprints</a>
        {% csrf_token %}
        {% if object %}<h3>Editar atributos del Sprint </h3>
        {% else %}<h3>Creación de Sprint</h3>{% endif %}
        {% if object %}<div>
            <label>Estado:</label> {{ object.estado }}
        </div>{% endif %}
        <div>
            <label> Duración estimada del Sprint (en días): </label>
            <input type="number" value="{{ object.duracion }}" name="duracion" min="1" required onchange="ver_horas()">
        </div>
        <div>
            <label> Horas de Trabajo disponibles del Sprint Team:</label>
            <p id="anuncio_hs_disponibles" style="display:inline"></p>
        </div>
        <div>
            <label> Horas de Trabajo asignadas en el Sprint Backlog: </label>
            <p id="anuncio_hs_utilizadas" style="display: inline"></p>
        </div>
        <div class="col-sm-6 col-md-6">
            <label id="id_sprintBacklog">Sprint Backlog:</label>
            <div class="pre-scrollable">
            <table class="table table-striped table-bordered ">
                <thead>
                <tr>
                    <td>#</td>
                    <td>User Story</td>
                    <td>Estado</td>
                    <td>Prioridad</td>
                    <td>Duracion</td>
                    <td>Asignar</td>
                </tr>
                </thead>
                <tbody>
                {% for US in US_list %}
                    <tr>
                    <td>
                    <input type="checkbox" name="sprintBacklog" value="{{ US.id }}"
                        onclick="seleccionar_backlog()" id="id_sprintBacklog_{{ US.id }}"
                           {% if US in object.sprintBacklog.all %}checked{% endif %} />
                    </td>
                    <td>{{ US.nombre }}</td>
                    <td>{{ US.get_estado_display  }}</td>
                    <td>{{ US.prioridad_final }}</td>
                    <td>{{ US.tiempo_estimado }}</td>
                    <td>
                    <select name="asignar_{{ US.id }}" id="id_asignar_{{ US.id }}" onchange="ver_horas()">
                        <option value="" selected>---------</option>
                    {% for team in proyecto.team_member_set.all %}
                        <option value="{{ team.id }}" {% if US.team_member == team %}selected{% endif %}>
                            {{ team.usuario.username }}
                        </option>
                    {% endfor %}
                    </select>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        </div>
        <div class="col-sm-5 col-md-5">
            <label>Participantes del Sprint:</label>
            <div class="pre-scrollable">
            <table class="table table-striped table-bordered ">
                <thead>
                <tr>
                    <td>#</td>
                    <td>Team Member</td>
                    <td>Disponibilidad diaria</td>
                    <td>Disponibilidad en el Sprint</td>
                    <td>Horas Asignadas</td>
                </tr>
                </thead>
                <tbody>
                {% for team in proyecto.team_member_set.all %}
                    <tr>
                    <td>
                    <input type="checkbox" name="sprintTeam" value="{{ team.id }}"
                        onclick="seleccionar_team()" id="id_sprintTeam_{{ team.id }}"
                           {% if team in object.sprintTeam.all %}checked{% endif %} />
                    </td>
                    <td>{{ team.usuario.username }}</td>
                    <td>{{ team.horas_trabajo }}</td>
                    <td><p id="hs_disp_{{ team.id }}"></p></td>
                    <td><p id="hs_asig_{{ team.id }}"></p></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
                </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <a class= "btn btn-danger" href="/proyecto/{{ proyecto.id }}/sprint/">Cancelar</a>
                    <button onclick="verificar()" class="btn btn-primary " type="submit">Guardar</button>
                </div>
            </div>
        </div>
    </form>
    <script>
        var us_ids = [{%for US in US_list %}{% if forloop.counter > 1%},{% endif %}{{US.id}}{% endfor %}]
        var us_hs = [{%for US in US_list %}{% if forloop.counter > 1%},{% endif %}{{US.tiempo_estimado}}{% endfor %}]
        var tm_ids = [{%for team in proyecto.team_member_set.all  %}{% if forloop.counter > 1%},{% endif %}{{team.id}}{% endfor %}]
        var tm_hs = [{%for team in proyecto.team_member_set.all  %}{% if forloop.counter > 1%},{% endif %}{{team.horas_trabajo}}{% endfor %}]
        console.log(us_ids)
        console.log(us_hs)
        console.log(tm_ids)
        console.log(tm_hs)
        function ver_horas() {
            var i;
            var total_asignado = 0;
            var total_disponible = 0;
            var dias = document.getElementsByName("duracion")[0].value
            for(i=0; i< tm_ids.length; i++){
                capacidad = document.getElementById("hs_disp_"+tm_ids[i])
                asignadas = document.getElementById("hs_asig_"+tm_ids[i])
                if ($('#id_sprintTeam_'+tm_ids[i]).is(":checked")){
                    total_disponible += tm_hs[i]
                    if(dias==""){
                        capacidad.innerText = "n/a"
                        asignadas.innerText = "n/a"
                    }else{
                        capacidad.innerText = tm_hs[i] * dias
                        var asg=  ver_asignados_por_team(tm_ids[i])
                        if (asg>tm_hs[i] * dias) {
                            asg = "<p style=\"display:inline;color:#ff6622;\">" + asg + "</p>"
                        }
                        asignadas.innerHTML = asg
                    }
                }else{
                    capacidad.innerText = ""
                    asignadas.innerText = ""
                }
            }
            for(i=0;i< us_ids.length; i++){
                if ($('#id_sprintBacklog_'+us_ids[i]).is(":checked")){
                    total_asignado += us_hs[i]
                }
            }
            if (dias!=""){
                total_disponible *= dias
                if (total_disponible<total_asignado){
                    total_asignado = total_asignado
                        + "<p style=\"display:inline;color:#ff6622;\"> ("
                        + (total_asignado-total_disponible) + " hs mas de lo previsto)</p>"
                }
            }else{
                total_disponible = "n/a"
            }

            document.getElementById("anuncio_hs_utilizadas").innerHTML = total_asignado
            document.getElementById("anuncio_hs_disponibles").innerHTML = total_disponible
        }
        function ver_asignados_por_team(tm_id) {
            var i;
            var ret=0;
            $("input[name=sprintBacklog]:checked").each(function () {
                var s = document.getElementById("id_asignar_"+this.value)
                if(s.options[s.selectedIndex].value==tm_id){
                    for(i=0;i< us_ids.length; i++){
                        if (us_ids[i]==this.value){
                            ret += us_hs[i];
                        }
                    }
                }
            });
            return ret;
        }
        function habilitar_asignacion() {
            var selec = $("input[name=sprintBacklog]:checked")
            var no_selec = $("input[name=sprintBacklog]:not(:checked)")
            selec.each(function () {
                var options = document.getElementById("id_asignar_"+this.value)
                options.hidden = false;
                options.disabled = false;
                options.required = true;
            });
            no_selec.each(function () {
                var options = document.getElementById("id_asignar_"+this.value)
                options.hidden = true;
                options.disabled = true;
                options.required = false;
            });
        }
        function habilitar_team() {
            var selec = $("input[name=sprintTeam]:checked")
            var no_selec = $("input[name=sprintTeam]:not(:checked)")
            selec.each(function(){
                var i,j;
                for (i=0;i<us_ids.length;i++){
                    var selec_team = document.getElementById("id_asignar_"+us_ids[i])
                    var op = selec_team.getElementsByTagName("option");
                    for (j=0;j< op.length; j++){
                        if(op[j].value == this.value){
                            op[j].hidden = false
                        }
                    }
                }
            });
            no_selec.each(function(){
                var i,j;
                for (i=0;i<us_ids.length;i++){
                    var selec_team = document.getElementById("id_asignar_"+us_ids[i])
                    var op = selec_team.getElementsByTagName("option");
                    for (j=0;j< op.length; j++){
                        if(op[j].value == this.value){
                            op[j].hidden = true
                        }
                    }
                    if(op[selec_team.selectedIndex].value == this.value){
                        for (j=0;j< op.length; j++){
                            if(op[j].value == ""){
                                selec_team.selectedIndex = j;
                            }
                        }
                    }
                }
            });
        }
        habilitar_asignacion();
        habilitar_team();
        ver_horas();
        function watch(lista,cantidad,validity,log){
            var k;
            var cant = $("input[name="+lista+"]:checked").length
            var boxes = document.getElementsByName(lista);
            console.log(log + " : "+ cant+"/"+boxes.length)
            if(cant==cantidad){
                for (k=0;k<boxes.length;k++){
                    boxes[k].setCustomValidity(validity);
                }
            }
        }

        function seleccionar_backlog() {
            watch('sprintBacklog',1,"","Sprint Backlog")
            habilitar_asignacion();
            ver_horas();
        }
        function seleccionar_team() {
            watch('sprintTeam',1,"","Sprint Team")
            habilitar_team()
            ver_horas()
        }
        function verificar() {
            watch('sprintBacklog',0,"El Sprint debe contar con al menos un User Story",
                "Cantidad de User Stories seleccionados");
            watch('sprintTeam',0,"El Sprint debe contar con al menos un Integrante",
                "Tamaño del equipo seleccionado");
        }
    </script>
    </form>
</div>
{% endblock %}

templates/sprint/borrar.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_proyectos.html" with proyecto=sprint.proyecto sprint_active=True %}
{% endblock %}

{% block title %}
    Sprints | Eliminar
{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
    <div class="container center-block">
        <p> </p>
        <h3>Confirmacion</h3>
	    <h4>&nbsp;¿Desea borrar el Sprint?</h4>
        <h5> Junto al Sprint, se borrán todas los resumenes de reuniones, no asi los User Stories</h5>
	    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
        <a class= "btn btn-default" href="/proyecto/{{ object.proyecto_id }}/sprint/">Cancelar</a>
    </div>
</form>
{% endblock %}

templates/sprint/burndownchart.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_proyectos.html" with proyecto=sprint.proyecto sprint_active=True %}
{% endblock %}

{% block title %}
    Sprint | Burndown Chart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a class= "btn btn-default" onclick=window.history.back()>Volver al Sprint</a>
                    <h4>Burndown Chart desde el {{ inicio_grafico }} hasta el {{ fin_grafico }}
                        <a class="btn btn-success" id="descargar" onclick="descargar()" >
                            <span class="glyphicon glyphicon-download-alt"/>
                        </a>
                    </h4>
                    <!--img src="/media/bc{{ sprint.id }}.png" class="img-responsive" alt="BurndownChart"-->

                    <canvas id="myChart" ></canvas>
<script>
    var ctx = document.getElementById("myChart").getContext('2d');
    var mixedChart = new Chart(ctx, {
        type: 'bar',
        data: {
            datasets: [{
                label: 'Trabajo pendiente estimado al finalizar el dia',
                data: [{% for y in eje_y %}{% if forloop.counter > 1%},{% endif %}'{{ y }}'{% endfor %}],
                backgroundColor: 'rgba(37, 199, 232, 0.5)'
            }, {
                label: 'Desempeño planificado',
                data:  [{% for y in eje_y_2 %}{% if forloop.counter > 1%},{% endif %}'{{ y }}'{% endfor %}],
                type: 'line',
                fill: false,
                borderColor: 'rgb(224, 11, 203)'
            }, {
                label: 'Desempeño estimado',
                data:  [{% for y in eje_y_3 %}{% if forloop.counter > 1%},{% endif %}'{{ y }}'{% endfor %}],
                type: 'line',
                fill: false,
                borderColor: 'rgb(224, 122, 23)',
                cubicInterpolationMode: 'monotone'
            }],
            labels: [{% for x in eje_x %}{% if forloop.counter > 1%},{% endif %}'{{ x }}'{% endfor %}]
        } ,
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero:true
                    }
                }],
                xAxes: [{
                    barPercentage : 0.5
                }]
            }
        }
    });
    function descargar() {
        var tag = document.getElementById("descargar")
        tag.download="BurnDownChart {{ proyecto.nombre }} {{ inicio_grafico }} - {{ fin_grafico }}"
        tag.href=mixedChart.toBase64Image()
    }
</script>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/sprint/control_calidad.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_proyectos.html" with proyecto=proyecto sprint_active=True %}
{% endblock %}



<!-- BOTÓN ACTIVO -->
{% block sprint_active %}
    active
{% endblock %}



{% block title %}
    Sprints | Control de calidad
{% endblock %}



{% block content %}
<div class="container">

<table class="table table-bordered">
    <h2>Proyecto {{ proyecto.nombre }}: Control de Calidad  Sprint {{ sprint }} </h2>
    <div><p> </p></div>
    <a class= "btn btn-default" href="/proyecto/{{ proyecto.id }}/sprint/{{ sprint.id }}">Volver al Sprint </a>


    <div><p> </p></div>
    <thead>
		<tr>
			<td>Nombre del US</td>
            <td>Estado del US</td>
            <td>Fase</td>
            <td>Subfase</td>
            <td></td>
		</tr>

</thead>
    <tbody>
        <div></div>
    {% if lista %}
		    {% for us in lista %}
		    <tr>

                <td>{{us.nombre}}</td>
                <td>{{us.get_estado_display}}</td>
                <td>{{us.fase_actual}}</td>
                <td>{{us.get_subfase_display}}</td>
			    <td>
                    <a class="btn btn-info"    href="/proyecto/{{ proyecto.id }}/sprint/{{ sprint.id }}/control/{{ us.id }}">Cambios</a>
                </td>
		    </tr>
		    {% endfor %}

		{% else %}
		    <h2>No hay registros de Sprints</h2>
            <div><p> </p></div>
		{% endif %}
</tbody>
</table>
<ul class="pagination">
	<li class="page-item">
		{% if page_obj.has_previous %}
       	 <a class="page-link" aria-label="Anterior" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a class="page-link" aria-label="Siguiente" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
    	{% endif %}
    </li>
</ul>
</div>

{% endblock %}

templates/sprint/control_scrum.html
{% extends 'base.html' %}

{% block tipo_navbar %}
    {% include "navbar_proyectos.html" with proyecto=proyecto sprint_active=True %}
{% endblock %}
<!-- BOTÓN ACTIVO -->
{% block sprint_active %}
    active
{% endblock %}


{% block title %}
    Sprints | Control de calidad
{% endblock %}



{% block content %}
<div class="container">

<table class="table table-bordered">
    <h2>Proyecto {{ proyecto.nombre }}: Control de US Sprint {{ sprint }}</h2>
    <div><p> </p></div>
    <a class= "btn btn-default" href="/proyecto/{{ proyecto.id }}/sprint/{{ sprint.id }}">Volver al Sprint</a>


    <div><p> </p></div>
    <thead>
		<tr>
			<td>Nombre del US</td>
            <td>Estado del US</td>
            <td>Fase</td>
            <td>Subfase</td>
            <td></td>
		</tr>

</thead>
    <tbody>
        <div></div>
    {% if lista %}
		    {% for us in lista %}
		    <tr>

                <td>{{us.nombre}}</td>
                <td>{{us.get_estado_display}}</td>
                <td>{{us.fase_actual}}</td>
                <td>{{us.get_subfase_display}}</td>
			    <td>
                    <a class="btn btn-info"    href="/proyecto/{{ proyecto.id }}/sprint/{{ sprint.id }}/control/{{ us.id }}">Cambios</a>
                </td>
		    </tr>
		    {% endfor %}

		{% else %}
		    <h2>No hay registros de us</h2>
            <div><p> </p></div>
		{% endif %}
</tbody>
</table>
<ul class="pagination">
	<li class="page-item">
		{% if page_obj.has_previous %}
       	 <a class="page-link" aria-label="Anterior" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a class="page-link" aria-label="Siguiente" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
    	{% endif %}
    </li>
</ul>
</div>

{% endblock %}