sgp/urls.py
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.urls import path
from django.conf.urls import url, include
from .views import PaginaPrincipalView, conectar, desconectar, Historial

app_name = 'sgp'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^principal$',PaginaPrincipalView.as_view(), name='principal'),
    url(r'^historial$',Historial.as_view(), name='historialSistema'),
    url(r'^login', conectar, name='login'),
    url(r'^logout', desconectar, name='logout'),
    url(r'^roles/', include(('roles.urls','roles'), namespace='roles')),
    url(r'^proyecto/', include(('proyectos.urls'), namespace='proyectos')),
    url(r'^usuarios/', include("usuarios.urls", namespace='usuarios')),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sprint/models.py
import datetime

from django.contrib.postgres.fields import ArrayField
from django.db import models


from sgp.settings import MEDIA_ROOT
from team.models import team_member
from userstory.models import UserStory
from proyectos.models import Proyecto

# === Modelos para sprint ===
class Sprint (models.Model):
    """
        Clase Sprint:
    Soporte para la seleccion de labores a cumplir en un determinado tiempo de ejecución.
    Las labores a contemplar serán determinadas en la clase UserStory
    """
    class Meta:
        """
        **Meta-Clase**:
        Establece los parametros de ordenamiento de los objetos de la clase.
        """
        ordering = ["estado","fechaFinalizacion"]
    estado = models.CharField(max_length=18,default="En espera")
    sprintBacklog = models.ManyToManyField(UserStory)
    sprintTeam = models.ManyToManyField(team_member)
    duracion = models.PositiveIntegerField(default=5)
    fechaInicio = models.DateField(null=True)
    fechaFinalizacion = models.DateField(null=True)
    proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
    notificadoFin = models.CharField(max_length=5,default='No')

    def __str__(self):
        return str(self.id)+str(self.proyecto.nombre)

    def save(self, force_insert=False, force_update=False, using=None,update_fields=None):
        if(self.estado!="En espera" and self.estado!="En ejecución" and self.estado!="Finalizado"):
            print("Estado no valido : "+self.estado)
            self.estado="En espera"
        if (self.fechaInicio!=None and self.fechaFinalizacion==None):
            calendario = datetime.timedelta(max(self.duracion-1,0))
            self.fechaFinalizacion = calendario + self.fechaInicio
        super().save(force_insert=force_insert,
                     force_update=force_update,
                     using=using,
                     update_fields=update_fields)

class reuniones (models.Model):
    """
        Clase Reuniones:
    Clase auxiliar que posibilita el registro de pequeñas reuniones retrospectivas dentro del Sprint.
    """
    class Meta:
        """
        **Meta-Clase**:
        Establece los parametros de ordenamiento de los objetos de la clase.
        """
        ordering = ["-fecha"]
    fecha = models.DateField()
    titulo = models.CharField(max_length=55)
    resumen = models.CharField(max_length=280)
    sprint = models.ForeignKey(Sprint,on_delete=models.CASCADE)


class BurndownChart(models.Model):
    sprint = models.ForeignKey(Sprint, on_delete=models.CASCADE)
    horas_restantes = models.IntegerField(default=0)
    contador_dias = models.IntegerField(default=1)
    ultima_fecha = models.DateField(auto_now_add=True)
    abscisas = ArrayField(models.DateField(), blank=True)
    ordenadas = ArrayField(models.IntegerField(blank=True), blank=True)

templates/reuniones/agregar.html
<div class="modal fade" id="agregarResumen" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<form method="post" action="{% url "proyectos:sprint:agregar_resumen" sprint.proyecto.id sprint.id %}">
  {% csrf_token %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div>
            <h3 class="modal-title" id="exampleModalLabel"><strong>Nuevo registro de Reunion</strong></h3>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div>
          <tr>
            <th><label for="id_titulo">Titulo:</label></th>
            <td><input type="text" name="titulo" id="id_titulo " required /></td>
          </tr>
        </div>
        <div>
          <tr>
            <th><label for="id_fecha">Fecha Realizada:</label></th>
            <td><input type="date" name="fecha" id="id_fecha" required /></td>
          </tr>
        </div>
      </div>
      <div class="modal-body">
        <tr>
            <th><label for="id_resumen">Resumen:</label></th>
            <td><input type="text" name="resumen" id="id_resumen" required /></td>
        </tr>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <input class="btn btn-primary" type="submit" value="Guardar" />
      </div>
    </div>
  </div>
</form>
</div>

templates/reuniones/borrar.html
<div class="modal fade" id="borrarResumen_{{reunion.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<form method="post" action="{% url "proyectos:sprint:borrar_resumen" reunion.sprint.proyecto.id reunion.sprint.id reunion.id %}">
  {% csrf_token %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div>
            <h3 class="modal-title"><strong>Confirmación</strong></h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
      </div>
      <div class="modal-body">
        <tr>¿Desea borrar el Resumen de la Reunion?</tr>
        <div>
          <tr>
            <th><strong>Titulo:</strong>{{ reunion.titulo }}</th>
          </tr>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <input class="btn btn-danger" type="submit" value="Borrar" />
      </div>
    </div>
  </div>
</form>
</div>

templates/reuniones/editar.html
<div class="modal fade" id="editarResumen_{{reunion.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<form method="post" action="{% url "proyectos:sprint:editar_resumen" reunion.sprint.proyecto.id reunion.sprint.id reunion.id %}">
  {% csrf_token %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div>
            <h3 class="modal-title" id="exampleModalLabel"><strong>Editar detalles de la Reunion</strong></h3>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div>
          <tr>
            <th><label for="id_titulo">Titulo:</label></th>
            <td><input type="text" name="titulo" value="{{ reunion.titulo }}" id="id_titulo " required /></td>
          </tr>
        </div>
        <div>
          <tr>
            <th><label for="id_fecha">Fecha Realizada:</label></th>
            <td><input type="date" name="fecha" value="{{ reunion.fecha|date:"Y-m-d" }}" id="id_fecha" required /></td>
          </tr>
        </div>
      </div>
      <div class="modal-body">
        <tr>
            <th><label for="id_resumen">Resumen:</label></th>
            <td><input type="text" name="resumen" value="{{ reunion.resumen}}" id="id_resumen" required /></td>
        </tr>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <input class="btn btn-primary" type="submit" value="Guardar Cambios" />
      </div>
    </div>
  </div>
</form>
</div>

templates/reuniones/ver.html
<div class="modal fade" id="verResumen_{{reunion.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div>
          <h3 class="modal-title" id="exampleModalLabel"><strong>Reunion Retrospectiva</strong></h3>
        </div>
        <div>
          <h5 class="modal-title" id="exampleModalLabel"><strong>Titulo:</strong> {{reunion.titulo }}</h5>
        </div>
        <div>
          <h5 class="modal-title" id="exampleModalLabel"><strong>Fecha realizada:</strong> {{reunion.fecha|date:"d/m/y" }} (Dia/Mes/Año)</h5>
        </div>
      </div>
      <div class="modal-body">
        <strong>Resumen: </strong>{{reunion.resumen }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>